services:
  web:
    build: .
    container_name: billiards_web
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    networks:
      - poolnet
  
  db:
    image: mysql:8.0
    container_name: billiards_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: poolroot
      MYSQL_DATABASE: Billiards
      MYSQL_USER: pooluser
      MYSQL_PASSWORD: poolpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d:ro
    networks:
      - poolnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: billiards_phpmyadmin
    restart: always
    depends_on:
    - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: poolroot
    ports:
      - "8081:80"
    networks:
      - poolnet

volumes:
  db_data:

networks:
  poolnet: